routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group( [ 'namespace' => 'App' , 'as' => 'app-auth.' ] , function() {
	\Illuminate\Support\Facades\Auth::routes();
} );
Route::group( [ 'as' => 'admin-auth.' , 'prefix' => 'v-admin' , 'namespace' => 'Admin' ] , function() {
	Route::redirect( '' , 'v-admin/login' );
	\Illuminate\Support\Facades\Auth::routes( [ 'register' => FALSE , 'emailVerify' => FALSE ] );

} );
Route::group( [ 'namespace' => 'Admin' , 'prefix' => 'v-admin' , 'as' => 'admin.' , 'middleware' => 'auth:admin' ] , function() {
	Route::get( '' , 'AdminController@dashboard' )->name( 'dashboard' );
	Route::group(['prefix'=>'profile','as'=>'profile.'],function(){
		Route::get('','AdminController@profile')->name('show');
		Route::post('edit/profile','AdminController@change')->name('change');
		Route::post('edit/password','AdminController@password')->name('password');
	});
	Route::group( [ 'prefix' => 'users' , 'as' => 'user.' ] , function() {
		Route::get( '' , 'UserController@index' )->name( 'index' );
		Route::delete( 'delete/{user}' , 'UserController@delete' )->name( 'delete' );
		Route::get( '/show/{user}' , 'UserController@show' )->name( 'show' );
	} );
	Route::group( [ 'prefix' => 'contants' , 'as' => 'contant.' ] , function() {
		Route::get( 'delete/{contant}' , 'ContantController@delete' )->name( 'delete' );
		Route::get( '' , 'ContantController@index' )->name( 'index' );
		Route::get('create','ContantController@create')->name('create');
		Route::post('store','ContantController@store')->name('store');
	} );
	Route::group( [ 'prefix' => 'account' , 'as' => 'account.' ] , function() {
		Route::get( '' , 'AdminController@index' )->name( 'index' );
		Route::get( 'create' , 'AdminController@create' )->name( 'create' );
		Route::post( 'create' , 'AdminController@store' )->name( 'store' );
		Route::delete( 'delete/{admin}' , 'AdminController@delete' )->name( 'delete' );
		Route::get( 'edit/{admin}' , 'AdminController@edit' )->name( 'edit' );
		Route::patch( 'update/{admin}' , 'AdminController@update' )->name( 'update' );
		Route::get('show/{admin}' , 'AdminController@show')->name('show');
	} );
	Route::group( [ 'prefix' => 'houses' , 'namespace' => 'House' , 'as' => 'houses.' ] , function() {
		Route::get( '' , 'HousesController@index' )->name( 'index' );
		Route::get( '/create' , 'HousesController@create' )->name( 'create' );
		Route::post( '/create' , 'HousesController@store' )->name( 'store' );
		Route::get( '/edit/{house}' , 'HousesController@edit' )->name( 'edit' );
		Route::post( '/edit/{house}' , 'HousesController@update' )->name( 'update' );
		Route::get( '/delete/{house}' , 'HousesController@delete' )->name( 'delete' );
    } );
	Route::group( [ 'prefix' => 'tickets' , 'as' => 'ticket.' ] , function() {
		Route::get( '' , 'TicketController@index' )->name( 'index' );
		Route::post( 'edit/{id}' , 'TicketController@update' )->name( 'update' );
		Route::get( 'edit/{ticket}' , 'TicketController@edit' )->name( 'edit' );
	} );
	Route::group( [ 'prefix' => 'agents' , 'as' => 'agent.' ] , function() {
		Route::get( '' , 'AgentController@index' )->name( 'index' );
		Route::get( 'edit/{agent}' , 'AgentController@edit' )->name( 'edit' );
		Route::post( 'edit/{id}' , 'AgentController@update' )->name( 'update' );
	} );
	Route::group( [ 'prefix' => 'blogs' , 'as' => 'blog.' , 'namespace' => 'Blog' ] , function() {
		Route::group( [ 'prefix' => 'categories' , 'as' => 'categories.' ] , function() {
            Route::get( '' , 'CategoryController@index' )->name( 'index' );
            Route::get( 'create' , 'CategoryController@create' )->name( 'create' );
			Route::post( 'create' , 'CategoryController@store' )->name( 'store' );
			Route::get( 'edit/{category}' , 'CategoryController@edit' )->name( 'edit' );
			Route::patch( 'update/{category}' , 'CategoryController@update' )->name( 'update' );
			Route::delete( 'delete/{category}' , 'CategoryController@delete' )->name( 'delete' );
		} );
		Route::group( [ 'prefix' => 'comments' , 'as' => 'comments.' ] , function() {
			Route::get( '' , 'CommentController@index' )->name( 'index' );
			Route::get( 'delete/{comment}' , 'CommentController@delete' )->name( 'delete' );
			Route::post( 'confirm/{comment}' , 'CommentController@confirm' )->name( 'confirm' );
			Route::post( 'update' , 'CommentController@update' )->name( 'update' );
		} );
		Route::group( [ 'prefix' => 'articles' , 'as' => 'articles.' ] , function() {
			Route::get( 'create' , 'ArticleController@create' )->name( 'create' );
			Route::get( '' , 'ArticleController@index' )->name( 'index' );
			Route::post( 'store' , 'ArticleController@store' )->name( 'store' );
			Route::get( 'delete/{article}' , 'ArticleController@delete' )->name( 'delete' );
			Route::get( 'edit/{article}' , 'ArticleController@edit' )->name( 'edit' );
			Route::post( 'update/{article}' , 'ArticleController@update' )->name( 'update' );
			Route::post('uploadImage' , 'ArticleController@uploadImage')->name('uploadImage');
	} );
		} );
	Route::group( [ 'prefix' => 'options' , 'as' => 'options.' ] , function() {
		Route::post('up-image' , 'OptionController@UploadImage') ->name('upImage');
		Route::group(['prefix'=>'about' , 'as'=>'about.'],function(){
			Route::get('','OptionController@about')->name('view');
			Route::post('','OptionController@saveAbout')->name('store');
		});
		Route::group(['prefix'=>'form/buyer' , 'as'=>'form.buyer.'],function(){
			Route::get('','OptionController@buyer')->name('view');
			Route::post('','OptionController@saveBuyer')->name('store');
		});
		Route::group(['prefix'=>'form/seller' , 'as'=>'form.seller.'],function(){
			Route::get('','OptionController@seller')->name('view');
			Route::post('','OptionController@saveSeller')->name('store');
		});
		Route::group( [ 'prefix' => 'home' , 'as' => 'home' ] , function() {
            Route::get( '' , 'OptionController@Home' );
            Route::post( '' , 'OptionController@UpdateHome' );
			Route::post( 'upload/ImageSlide' , 'OptionController@imageSlider' )->name( '.imageSlider' );
			Route::post( 'upload/ImageQSearch' , 'OptionController@ImageQSearch' )->name( '.ImageQSearch' );
		} );
		Route::group( [ 'prefix' => 'general' , 'as' => 'general' ] , function() {
			Route::get( '' , 'OptionController@General' );
			Route::post( '' , 'OptionController@UpdateGeneral' );
			Route::post('add/media','OptionController@addMedia')->name('addMedia');
		} );
	} );
} );
Route::group( [ 'as' => 'App.' , 'namespace' => 'App' ] , function() {
	Route::get( '' , "HomeController@Home" )->name( 'Home' );
	Route::group( [ 'as' => 'profile' , 'prefix' => 'profile' , 'middleware' => 'auth' ] , function() {
        Route::get( '' , 'UserController@profile' )->name( '' );
        Route::post( 'change-avatar' , 'UserController@avatar' )->name( '.change-avatar' );
		Route::post( 'changePassword' , 'UserController@changePassword' )->name( '.changePassword' );
		Route::post( 'updateProfile' , 'userController@update' )->name( '.update' );
	} );
	Route::get('about','PageController@about')->name('about');
	Route::get( 'contact' , 'ContantController@contact' )->name( 'contact' );
	Route::group( [ 'prefix' => 'blogs' , 'as' => 'blog.' , 'namespace' => 'Blog' ] , function() {
		Route::get( 'article/{article}' , 'ArticleController@show' )->name( 'show' );
		Route::get( 'archive' , 'ArticleController@archive' )->name( 'archive' );
        Route::post('store/{article}', 'ArticleController@store')->name('store');
	} );
	Route::group( [ 'prefix' => 'houses' , 'as' => 'house.' , 'namespace' => 'House' ] , function() {
		Route::get( '/{MLSNumber}/{Address}' , 'HouseController@show' )->name( 'show' );
		Route::get( '' , 'HouseController@archive' )->name( 'index' );
	} );
	Route::group( [ 'prefix' => 'forms' , 'as' => 'form.' ] , function() {
		Route::post( 'buy' , 'TicketController@Buy' )->name( 'buy' );
		Route::get( 'sell' , 'TicketController@showSellingForm' )->name( 'showSellingForm' );
		Route::get( 'buy' , 'TicketController@showBuyingForm' )->name( 'showBuyingForm' );
		Route::post( 'sell' , 'TicketController@Sell' )->name( 'sell' );
		Route::post( 'ticket' , 'TicketController@contact' )->name( 'TicketContact' );
        Route::post( 'store' , 'TicketController@store' )->name( 'store' );
    } );
} );

app/Http/Controllers/Admin/Blog/ArticleController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Admin;
use App\Article;
use App\Category;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ArticleController extends Controller
{
	public function index ()
	{
		$now = Carbon::now()->format( 'yy-m-d h:i:s' );
		$rq = request();
		$articles = Article::query();
		if ( $rq[ 'categories' ] ) {
			$articlesCategories = \DB::table( 'article_category' )->whereIn( 'category_id' , $rq[ 'categories' ] )->get( 'article_id' )->pluck( 'article_id' )->toArray();
			$articles = $articles->whereIn( 'id' , $articlesCategories );
		}
		if ( $rq[ 'title' ] ) {
			$articles = $articles->where( 'title' , 'like' , '%' . $rq[ 'title' ] . '%' );
		}
		if ( $rq[ 'tags' ] ) {
			$articles = $articles->where( function( Builder $query ) use ( $rq ) {
				foreach ( $rq[ 'tags' ] as $tag ) {
					$query = $query->orWhere( 'tag' , 'like' , '%' . $tag . '%' );
				}
			} );
		}
		if ( $rq[ 'authors' ] ) {
			$articles = $articles->whereIn( 'admin_id' , $rq[ 'authors' ] );
		}
		if ( $rq[ 'status' ] ) {
			$status = $rq[ 'status' ];
			if ( $status == 'Draft' or $status == 'UnPublish' ) {
				$articles = $articles->where( 'status' , Article::$Status[ $status ] );
			}
			if ( $status == 'Published' ) {
				$articles = $articles->where( 'status' , Article::$Status[ 'Publish' ] )->whereDate( 'releaseTime' , '<=' , $now );
			}
			if ( $status == 'PendingPublish' ) {
				$articles = $articles->where( 'status' , Article::$Status[ 'Publish' ] )->whereDate( 'releaseTime' , '>' , $now );
			}
		}
		$count = [
			'All'            => Article::count() ,
			'Draft'          => Article::where( 'status' , Article::$Status[ 'Draft' ] )->count() ,
			'UnPublish'      => Article::where( 'status' , Article::$Status[ 'UnPublish' ] )->count() ,
			'Published'      => Article::where( 'status' , Article::$Status[ 'Publish' ] )->whereDate( 'releaseTime' , '<=' , $now )->count() ,
			'PendingPublish' => Article::where( 'status' , Article::$Status[ 'Publish' ] )->whereDate( 'releaseTime' , '>' , $now )->count()
		];
		$articles = $articles->latest( 'releaseTime' )->paginate( 10 );
		$categories = Category::whereNull( 'parentCategory' )->get();
		$tags = Article::all( 'tag' )->pluck( 'tag' )->collapse()->unique();
		$authors = Admin::all();
		return view( 'Admin.Blog.Articles.index' , compact( [ 'articles' , 'authors' , 'tags' , 'categories' , 'count' ] ) );
	}
	
	public function create ()
	{
		$article = FALSE;
		return view( 'Admin.Blog.Articles.create' )->with( 'article' , $article );
	}
	
	public function store ( Request $request )
	{
		$this->validate( $request , [
			'title'         => 'required' ,
			'body'          => 'required' ,
			'featuredImage' => 'required|mimes:jpeg,bmp,png' ,
			'category'      => 'required' ,
			'tag'           => 'required' ,
			'publishTime'   => 'required' ,
			'status'        => 'required' ,
		] );
		//Generate Data
		$data = $request->except( 'category' , 'publishTime' );
		$data[ 'releaseTime' ] = Carbon::parse( $request->input( 'publishTime' ) )->format( 'yy-m-d h:i:s' );
		$data[ 'slug' ] = Str::slug( $data[ 'title' ] );
		//Upload image
		$img = $request->file( 'featuredImage' );
		$imageArticle = $img->store( 'articles/featuredImage' , [ 'disk' => 'public' ] );
		$data[ 'featuredImage' ] = \Storage::url( $imageArticle );
		//Create Article
		$article = Auth::guard( 'admin' )->user()->Articles()->create( $data );
		$article->categories()->attach( $request->input( 'Category' ) );
		return redirect()->route( 'admin.blog.articles.index' )->with( 'success' , ' The article create successfully' );
	}
	
	public function delete ( Article $article )
	{
		$article->delete();
		return back()->with( 'delete' , 'The article delete successfully' );
	}
	
	public function edit ( Article $article )
	{
		return view( 'Admin.Blog.Articles.edit' )->with( 'article' , $article );
	}
	
	public function update ( Request $request , Article $article )
	{
		$this->validate( $request , [
			'title'         => 'required' ,
			'body'          => 'required' ,
			'featuredImage' => 'mimes:jpeg,bmp,png' ,
			'category'      => 'required' ,
			'tag'           => 'required' ,
			'publishTime'   => 'required' ,
			'status'        => 'required' ,
		] );
		//Generate Data
		$data = $request->except( [ 'publishTime' , 'category' ] );
		$data[ 'slug' ] = Str::slug( $data[ 'title' ] );
		$data[ 'releaseTime' ] = Carbon::parse( $request->input( 'publishTime' ) )->format( 'yy-m-d h:i:s' );
		//Upload File//
		if ( $request->hasFile( 'featuredImage' ) ) {
			$image = $request->file( 'featuredImage' );
			$image = $image->store( 'articles/featuredImage' , [ 'disk' => 'public' ] );
			$data[ 'featuredImage' ] = Storage::url( $image );
		}
		//Update Article
		$article->update( $data );
		$article->categories()->sync( [ $request->input( 'category' ) ] );
		return redirect()->route( 'admin.blog.articles.index' )->with( 'update' , ' The article update successfully' );
	}
	
	public function uploadImage ( Request $request )
	{
		$request->validate( [
			'image' => 'required|mimetypes:image/jpeg,image/png'
		] );
		$file = $request->file( 'image' );
		$file = $file->store( '/articles' , [ 'disk' => 'public' ] );
		$response = [
			'location'  => Storage::url( $file ) ,
			'success'   => TRUE ,
			'csrfToken' => csrf_token()
		];
		return response()->json( $response );
	}
}

app/Http/Controllers/Admin/Blog/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
	public function index ()
	{
		$categories = Category::whereNull( 'parentCategory' )->get();
		return view( 'Admin.Blog.Categories.index' )->with( [ 'categories' => $categories ] );
	}
	
	public function create ()
	{
		return view( 'Admin.Blog.Categories.create' );
	}
	
	public function store ( Request $request )
	{
		$request->validate( [
			'name'            => 'required' ,
			'slug'            => 'required|unique:categories' ,
			'metaTitle'       => 'required' ,
			'metaKeywords'    => 'required' ,
			'metaDescription' => 'required' ,
		] );
		Category::create( $request->all() );
		return redirect()->route( 'admin.blog.categories.index' );
	}
	
	public function edit ( Category $category )
	{
		return view( 'Admin.Blog.Categories.edit' )->with( [ 'category' => $category ] );
	}
	
	public function update ( Category $category , Request $request )
	{
		$rolls = [ 'name' => 'required' , 'slug' => 'required' ];
		$request->input( 'slug' ) != $category->slug ? $rolls[ 'slug' ] = 'required|unique:categories' : NULL;
		$request->validate( $rolls );
		$category->update( $request->all() );
		return redirect()->route( 'admin.blog.categories.index' );
	}
	
	public function delete ( Category $category )
	{
		try {
			$category->delete();
		} catch ( \Exception $e ) {
			return back()->with('error' , $e->getMessage());
		}
		return redirect()->route( 'admin.blog.categories.index' );
	}
}

app/Http/Controllers/Admin/Blog/CommentController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Comment;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;

class CommentController extends Controller
{
	public function index ()
	{
		$comments = Comment::all();
		return view( 'Admin.Blog.Comments.index' )->with( [ "comments" => $comments ] );
	}
	
	public function update ( Request $request )
	{
		$comment = Comment::find( $request->input( 'id' ) );
		$comment->update( [ 'body' => $request->input( 'comment' ) ] );
		return response()->json( [ 'update' => 'Comment Updated' ] );
	}
	
	public function delete ( Comment $comment )
	{
		$comment->delete();
		return back();
	}
	
	public function confirm ( Comment $comment )
	{
		if ( $comment->confirmComment ) {
			$comment->confirmComment = NULL;
		} else {
			$comment->confirmComment = Carbon::now();
		}
		$comment->save();
		return back();
	}
}

resources/views/Admin/Blog/Comments/index.blade.php
@extends('Admin.Template.layout')
@section('content')
	@include('Admin.Template.notification')
	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">ListRequest:</h6>
		</div>
		<div class="card-body">
			<form class="" action="{{request()->fullUrl()}}">
				<div class="row" style="padding-bottom: 10px;">
					<div class="col-md-2 col -sm-12-col-xl-1">
						<select name="ticketType" id="ticketType" class="form-control">
							<option value {{request('ticketType')? 'selected' : NULL}}>Select Ticket Type</option>
							<option value="0" {{request('ticketType') === 0 ? 'selected':NULL}}>But</option>
							<option value="1" {{request('ticketType') === 1 ? 'selected':NULL}}>Sell</option>
						</select>
					</div>
					<div class="col-md-3 col-sm-12 col-xl-2">
						<input type="hidden" name="type" value="{{old('type')}}">
						<input type="text" class="form-control" placeholder="Name" name="name" value="{{request('name')}}">
					</div>
					<div class="col-md-3 col-sm-12 col-xl-2">
						<input type="email" class="form-control" placeholder="Email" name="email" value="{{request('email')}}">
					</div>
					<div class="col-md-4 col-sm-12 col-xl-3">
						<input type="text" name="phone" class="form-control" placeholder="Enter Phone Number" value="{{old('phone')}}">
					</div>
					<div class="col-sm-2 col-sn-12 col-xl-2">
						<button type="submit" class="btn btn-outline-primary">Apply</button>
					</div>
				</div>
			</form>
			<table class="table table-bordered table-hover" border="5">
				<thead>
				<tr>
					<th style="text-align: center">Name</th>
					<th style="text-align: center">Email</th>
					<th style="text-align: center">Comment</th>
					<th style="text-align: center">Article</th>
					<th style="text-align: center">Confirm</th>
					<th style="text-align: center">Setting
				</tr>
				</thead>
				<tbody>
				@foreach($comments as $comment)
					<tr commentId="{{$comment->id}}">
						<td>{{$comment->user->name??$comment->admin->id??NULL}}</td>
						<td>{{$comment->user->email??$comment->admin->id??NULL}}</td>
						<td class="CommentBody">
							<p data-CommentId="{{$comment->id}}" style="width:100%;">{{$comment->body}}</p>
							<div class="btn-group-vertical comment-update-btns" style="display: none">
								<button onclick="update({{$comment->id}} , event)" class="btn btn-success">Update
								</button>
								<button onclick="cancel(event)" class="btn btn-success">Cancel</button>
							</div>
							<button onclick="edit(event)" class="btn btn-success comment-edit">Edit</button>
						</td>
						<td>{{$comment->article->title??NULL}}</td>
						<td>{{$comment->confirmComment?'Confirmed' : 'NotConfirmed'}}</td>
						<td>
							<form action="{{route('admin.blog.comments.confirm' , $comment)}}" method="post">
								@csrf
								<div class="btn-group">
									<a href="{{route('admin.blog.comments.delete' , $comment)}}" class="btn btn-danger">Delete</a>
									<button class="btn btn-info" type="submit">{{$comment->confirmComment?'NotConfirm' : 'Confirm'}}</button>
								</div>
							</form>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>
	</div>
@endsection
@section('css')
	<style>
		td.CommentBody {
			position: relative;
		}
		
		button.btn.btn-success.comment-edit::-webkit-scrollbar {
			display: none;
		}
		
		button.btn.btn-success.comment-edit {
			position: absolute;
			top: 0;
			right: 0;
			bottom: 0;
			border-radius: 0;
			overflow-x: hidden;
			padding: 0;
			margin: 0;
			width: 0;
			transition: 0.5s;
			border: 0;
		}
		
		button.btn.btn-success.comment-edit {
			display: -webkit-inline-box;
		}
		
		td.CommentBody:hover > .comment-edit {
			padding: inherit;
			margin: inherit;
			width: 51px;
			border: initial;
			transition: 0.5s;
		}
		
		.btn-group-vertical.comment-update-btns {
			position: absolute;
			top: 0;
			right: 0;
			bottom: 0;
		}
		
		.btn-group-vertical.comment-update-btns > .btn {
			border-radius: 0;
		}
	</style>
@endsection
@section('js')
	<script>
        function edit(e) {
            let target = $(e.target)
            let p = target.prev().prev();
            let comment = p.text();
            let textarea = $("<textarea></textarea>");
            textarea.val(comment);
            textarea.css("width", "calc(100% - 80px)")
            p.after(textarea);
            p.remove()
            target.hide();
            target.prev().show()
        }

        function cancel(e) {
            let target = $(e.target)
            let t = target.parent().prev();
            let comment = t.val();
            let p = $("<p></p>");
            p.text(comment);
            p.css("width", "100%")
            t.after(p);
            t.remove()
            target.parent().hide();
            target.parent().next().show();
        }

        function update(commentId, e) {
            let target = $(e.target)
            let comment = target.parent().prev().val();
            let token = '{{csrf_token()}}' ;
            $.post('{{route('admin.blog.comments.update')}}' , {!!  "{'_token' : token , id: commentId,comment: comment}" !!}).done(function (response) {
                let p = $("<p></p>");
                let t = target.parent().prev();
                p.text(comment);
                p.css("width", "100%")
                t.after(p);
                t.remove()
                target.parent().hide();
                target.parent().next().show();
            });
        }
	</script>
@endsection