routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group( [ 'namespace' => 'App' , 'as' => 'app-auth.' ] , function() {
	\Illuminate\Support\Facades\Auth::routes();
} );
Route::group( [ 'as' => 'admin-auth.' , 'prefix' => 'v-admin' , 'namespace' => 'Admin' ] , function() {
	Route::redirect( '' , 'v-admin/login' );
	\Illuminate\Support\Facades\Auth::routes( [ 'register' => FALSE , 'emailVerify' => FALSE ] );

} );
Route::group( [ 'namespace' => 'Admin' , 'prefix' => 'v-admin' , 'as' => 'admin.' , 'middleware' => 'auth:admin' ] , function() {
	Route::get( '' , 'AdminController@dashboard' )->name( 'dashboard' );
	Route::group(['prefix'=>'profile','as'=>'profile.'],function(){
		Route::get('','AdminController@profile')->name('show');
		Route::post('edit/profile','AdminController@change')->name('change');
		Route::post('edit/password','AdminController@password')->name('password');
	});
	Route::group( [ 'prefix' => 'users' , 'as' => 'user.' ] , function() {
		Route::get( '' , 'UserController@index' )->name( 'index' );
		Route::delete( 'delete/{user}' , 'UserController@delete' )->name( 'delete' );
		Route::get( '/show/{user}' , 'UserController@show' )->name( 'show' );
	} );
	Route::group( [ 'prefix' => 'contants' , 'as' => 'contant.' ] , function() {
		Route::get( 'delete/{contant}' , 'ContantController@delete' )->name( 'delete' );
		Route::get( '' , 'ContantController@index' )->name( 'index' );
		Route::get('create','ContantController@create')->name('create');
		Route::post('store','ContantController@store')->name('store');
	} );
	Route::group( [ 'prefix' => 'account' , 'as' => 'account.' ] , function() {
		Route::get( '' , 'AdminController@index' )->name( 'index' );
		Route::get( 'create' , 'AdminController@create' )->name( 'create' );
		Route::post( 'create' , 'AdminController@store' )->name( 'store' );
		Route::delete( 'delete/{admin}' , 'AdminController@delete' )->name( 'delete' );
		Route::get( 'edit/{admin}' , 'AdminController@edit' )->name( 'edit' );
		Route::patch( 'update/{admin}' , 'AdminController@update' )->name( 'update' );
		Route::get('show/{admin}' , 'AdminController@show')->name('show');
	} );
	Route::group( [ 'prefix' => 'houses' , 'namespace' => 'House' , 'as' => 'houses.' ] , function() {
		Route::get( '' , 'HousesController@index' )->name( 'index' );
		Route::get( '/create' , 'HousesController@create' )->name( 'create' );
		Route::post( '/create' , 'HousesController@store' )->name( 'store' );
		Route::get( '/edit/{house}' , 'HousesController@edit' )->name( 'edit' );
		Route::post( '/edit/{house}' , 'HousesController@update' )->name( 'update' );
		Route::get( '/delete/{house}' , 'HousesController@delete' )->name( 'delete' );
    } );
	Route::group( [ 'prefix' => 'tickets' , 'as' => 'ticket.' ] , function() {
		Route::get( '' , 'TicketController@index' )->name( 'index' );
		Route::post( 'edit/{id}' , 'TicketController@update' )->name( 'update' );
		Route::get( 'edit/{ticket}' , 'TicketController@edit' )->name( 'edit' );
	} );
	Route::group( [ 'prefix' => 'agents' , 'as' => 'agent.' ] , function() {
		Route::get( '' , 'AgentController@index' )->name( 'index' );
		Route::get( 'edit/{agent}' , 'AgentController@edit' )->name( 'edit' );
		Route::post( 'edit/{id}' , 'AgentController@update' )->name( 'update' );
	} );
	Route::group( [ 'prefix' => 'blogs' , 'as' => 'blog.' , 'namespace' => 'Blog' ] , function() {
		Route::group( [ 'prefix' => 'categories' , 'as' => 'categories.' ] , function() {
            Route::get( '' , 'CategoryController@index' )->name( 'index' );
            Route::get( 'create' , 'CategoryController@create' )->name( 'create' );
			Route::post( 'create' , 'CategoryController@store' )->name( 'store' );
			Route::get( 'edit/{category}' , 'CategoryController@edit' )->name( 'edit' );
			Route::patch( 'update/{category}' , 'CategoryController@update' )->name( 'update' );
			Route::delete( 'delete/{category}' , 'CategoryController@delete' )->name( 'delete' );
		} );
		Route::group( [ 'prefix' => 'comments' , 'as' => 'comments.' ] , function() {
			Route::get( '' , 'CommentController@index' )->name( 'index' );
			Route::get( 'delete/{comment}' , 'CommentController@delete' )->name( 'delete' );
			Route::post( 'confirm/{comment}' , 'CommentController@confirm' )->name( 'confirm' );
			Route::post( 'update' , 'CommentController@update' )->name( 'update' );
		} );
		Route::group( [ 'prefix' => 'articles' , 'as' => 'articles.' ] , function() {
			Route::get( 'create' , 'ArticleController@create' )->name( 'create' );
			Route::get( '' , 'ArticleController@index' )->name( 'index' );
			Route::post( 'store' , 'ArticleController@store' )->name( 'store' );
			Route::get( 'delete/{article}' , 'ArticleController@delete' )->name( 'delete' );
			Route::get( 'edit/{article}' , 'ArticleController@edit' )->name( 'edit' );
			Route::post( 'update/{article}' , 'ArticleController@update' )->name( 'update' );
			Route::post('uploadImage' , 'ArticleController@uploadImage')->name('uploadImage');
	} );
		} );
	Route::group( [ 'prefix' => 'options' , 'as' => 'options.' ] , function() {
		Route::post('up-image' , 'OptionController@UploadImage') ->name('upImage');
		Route::group(['prefix'=>'about' , 'as'=>'about.'],function(){
			Route::get('','OptionController@about')->name('view');
			Route::post('','OptionController@saveAbout')->name('store');
		});
		Route::group(['prefix'=>'form/buyer' , 'as'=>'form.buyer.'],function(){
			Route::get('','OptionController@buyer')->name('view');
			Route::post('','OptionController@saveBuyer')->name('store');
		});
		Route::group(['prefix'=>'form/seller' , 'as'=>'form.seller.'],function(){
			Route::get('','OptionController@seller')->name('view');
			Route::post('','OptionController@saveSeller')->name('store');
		});
		Route::group( [ 'prefix' => 'home' , 'as' => 'home' ] , function() {
            Route::get( '' , 'OptionController@Home' );
            Route::post( '' , 'OptionController@UpdateHome' );
			Route::post( 'upload/ImageSlide' , 'OptionController@imageSlider' )->name( '.imageSlider' );
			Route::post( 'upload/ImageQSearch' , 'OptionController@ImageQSearch' )->name( '.ImageQSearch' );
		} );
		Route::group( [ 'prefix' => 'general' , 'as' => 'general' ] , function() {
			Route::get( '' , 'OptionController@General' );
			Route::post( '' , 'OptionController@UpdateGeneral' );
			Route::post('add/media','OptionController@addMedia')->name('addMedia');
		} );
	} );
} );
Route::group( [ 'as' => 'App.' , 'namespace' => 'App' ] , function() {
	Route::get( '' , "HomeController@Home" )->name( 'Home' );
	Route::group( [ 'as' => 'profile' , 'prefix' => 'profile' , 'middleware' => 'auth' ] , function() {
        Route::get( '' , 'UserController@profile' )->name( '' );
        Route::post( 'change-avatar' , 'UserController@avatar' )->name( '.change-avatar' );
		Route::post( 'changePassword' , 'UserController@changePassword' )->name( '.changePassword' );
		Route::post( 'updateProfile' , 'userController@update' )->name( '.update' );
	} );
	Route::get('about','PageController@about')->name('about');
	Route::get( 'contact' , 'ContantController@contact' )->name( 'contact' );
	Route::group( [ 'prefix' => 'blogs' , 'as' => 'blog.' , 'namespace' => 'Blog' ] , function() {
		Route::get( 'article/{article}' , 'ArticleController@show' )->name( 'show' );
		Route::get( 'archive' , 'ArticleController@archive' )->name( 'archive' );
        Route::post('store/{article}', 'ArticleController@store')->name('store');
	} );
	Route::group( [ 'prefix' => 'houses' , 'as' => 'house.' , 'namespace' => 'House' ] , function() {
		Route::get( '/{MLSNumber}/{Address}' , 'HouseController@show' )->name( 'show' );
		Route::get( '' , 'HouseController@archive' )->name( 'index' );
	} );
	Route::group( [ 'prefix' => 'forms' , 'as' => 'form.' ] , function() {
		Route::post( 'buy' , 'TicketController@Buy' )->name( 'buy' );
		Route::get( 'sell' , 'TicketController@showSellingForm' )->name( 'showSellingForm' );
		Route::get( 'buy' , 'TicketController@showBuyingForm' )->name( 'showBuyingForm' );
		Route::post( 'sell' , 'TicketController@Sell' )->name( 'sell' );
		Route::post( 'ticket' , 'TicketController@contact' )->name( 'TicketContact' );
        Route::post( 'store' , 'TicketController@store' )->name( 'store' );
    } );
} );

resources/views/App/Template/footer.blade.php
<footer class="container-fluid footer mt-3 position-relative">
	<div class="container">
		<div class="row">
			<div class="box-plan position-absolute w-25">
				<img class="plan" src="images/plan.svg" alt="">
			</div>
			<div class="col-lg-8">
				<div class="row title-section footer-title py-4">
					<div class="col-12 ">
						<div class="title-area text-center">
							<h3 class="clr-ff fs-23">
								Get In Touch
							</h3>
						</div>
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-12">
						<form id="myForm" action="{{route('App.form.store')}}" method="post">
							<div class="row">
								<div class="col-6">
									<input type="text" class="form-control" placeholder="Your Name *" id="name">
									<input type="email" class="form-control" placeholder="Your Email *" id="email">
									<input type="tel" class="form-control" placeholder="Your phone *" id="tel">
								</div>
								<div class="col-6">
									<textarea class="form-control" id="mes" name="name" rows="5" cols="40" placeholder="Your message" *></textarea>
								</div>
							</div>
							<button type="submit"  id="ajaxSubmit" class="btn btn-warning btn-round hd-font fs-12 mt-3">Send Message
							</button>
						</form>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="row title-section footer-title py-4">
					<div class="col-12 ">
						<div class="title-area text-center">
							<h3 class="clr-ff fs-23">
								OFFICE INFO
							</h3>
						</div>
					</div>
				</div>
				<hr>
				<div class="info-box">
					<div class="address-info">
						<figure class="text-left mb-0">
							<i class="fal fa-map-pin clr-ef te-sh fs-23"></i>
							<p class="clr-ef fs-17">2397 Marine Dr.West Vancouver BC, V7V 1K9</p>
						</figure>
					</div>
					<div class="phone-info mt-4">
						<figure class="text-left mb-0">
							<i class="fal fa-mobile clr-ef te-sh fs-23"></i>
							<span class="clr-ef fs-17"> 604.500.1010</span>
						</figure>
					</div>
					<div class="email-info ">
						<figure class="text-left m-0">
							<i class="fal fa-envelope clr-ef te-sh fs-23"></i>
							<span class="clr-ef fs-17">amir@hamzehali.com</span>
						</figure>
					</div>


				</div>
			</div>
		</div>
	</div>
</footer>
<section class="container-fluid copyright py-3 text-center clr-ff">
	<p class="m-0">Real Estate Website by RealtyNinja Privacy Policy</p>
</section>

resources/views/App/Template/header.blade.php
<header class="container-fluid header-area">
	<div class="container">
		<div class="row logo-area">
			<div class="d-none d-md-block col-md-3 col-lg-4"></div>
			<div class="col-12 col-md-6 col-lg-4 logo">
				<div class="logo-area text-center">
					<a href="#">
						<img src="/images/logo.png" alt="">
					</a>
				</div>
			</div>
			<div class="d-none d-md-block col-md-3 col-lg-4"></div>
		</div>
		<div class="row nav-menu">
			<div class="col-lg-3 text-center text-lg-left m-auto">
				<div class="phone-num d-inline-block mt-3">
					<figure>
						<i class="fal fa-phone clr-ef te-sh fs-23"></i>
						<span class="clr-ff hd-font fs-16">604.500.1010</span>
					</figure>
				</div>
				<div class="account-btn d-inline-block ml-4 mt-3">
					@guest('web')
						<figure data-toggle="modal" data-target="#loginform">
							<i class="fal fa-user clr-ef te-sh fs-23"></i>
							<!-- Button trigger modal -->
							<span class="clr-ff hd-font fs-16">Account</span>
						</figure>
					@else()
						<a href="{{route('App.profile')}}">
							<i class="fal fa-user-check clr-ef te-sh fs-23"></i>
							<!-- Button trigger modal -->
							<span class="clr-ff hd-font fs-16">Profile</span>
						</a>
						<a href="{{route('app-auth.logout')}}" onclick="logout(event , '{{route('app-auth.logout')}}')">
							<i class="fal fa-door-open clr-ef te-sh fs-23"></i>
							<!-- Button trigger modal -->
							<span class="clr-ff hd-font fs-16">Logout</span>
						</a>
				@endguest()
				<!-- Modal -->
					<div class="modal fade" id="loginform" tabindex="-1" role="dialog" aria-labelledby="loginlabel" aria-hidden="true">
						<div class="modal-dialog modal-lg" role="document">
							<div class="modal-content bg-2c">
								<div class="modal-header row">
									<div class="col-lg-6">
										<div class="title-section-modal py-4">
											<div class="col-12 ">
												<div class="title-area text-left">
													<h5 class="clr-ef fs-20" id="loginlabel">
														Create A Free Account
													</h5>
												</div>
											</div>
										</div>
									</div>
									<div class="col-lg-6">
										<div class="title-section-modal py-4">
											<div class="col-12 ">
												<div class="title-area text-left">
													<h5 class="clr-ef fs-20">
														Login To Your Account
													</h5>
												</div>
											</div>
										</div>
									</div>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body row">
									<div class="col-lg-6">
										<form action="{{route('app-auth.register')}}" id="registerForm">
											<input type="text" name="name" class="form-control" placeholder="Your Name *">
											<input type="email" name="email" class="form-control" placeholder="Your Email *">
											<input type="tel" name="phone" class="form-control" placeholder="Your phone *">
											<input type="password" name="password" class="form-control" placeholder="Create Your Password *">
											<input type="password" name="password_confirmation" class="form-control" placeholder="Repeat Your Password *">
											<div class="form-check mt-4">
												<label class="form-check-label">
													<input class="form-check-input" type="checkbox" name="accept" value="">
													I agree to the privacy policy and consent to receiving real estate
													related emails from this website (you can unsubscribe at any time).
													<span class="form-check-sign">
															<span class="check"></span>
													</span>
												</label>
											</div>
											<button type="submit" class="btn btn-warning btn-round hd-font fs-14 mt-3">
												Register
											</button>
										</form>
									</div>
									<div class="col-lg-6 brd-left">
										<form action="{{route('app-auth.login')}}" id="loginForm" enctype="multipart/form-data">
											<input type="email" class="form-control" name="email" placeholder="Your Email *">
											<input type="password" class="form-control" name="password" placeholder="Your Password *">
											<div class="form-check">
												<label class="form-check-label">
													<input class="form-check-input" type="checkbox" name="remember">
													<span class="form-check-sign"><span class="check"></span></span>Remember
													me
												</label>
											</div>
											<button type="submit" class="btn btn-warning btn-round hd-font fs-14 mt-3">
												Login
											</button>
											<span class="clr-ef">Forgot your password? <a href="#" class="reset_link clr-blue">Reset it</a>.</span>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-6 text-center">
				<div class="nav-menu hd-font">
					@include('App.Template.navBar')
				</div>
			</div>
			@php($Social = \App\Option::SocialMedia()->value)
			<div class="col-lg-3 text-center text-lg-right m-auto">
				<div class="social-icon">
					@foreach($Social??[] as $s)
						<a href="{{$s['Link']}}" class="btn btn-secondary btn-fab btn-round">
							<i class="fab fa-{{$s['Icon']}}"></i>
						</a>
					@endforeach
				</div>
			</div>
		</div>
	</div>
</header>
<!--Start-->

resources/views/App/Template/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="_token" content="{{csrf_token()}}">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="X-CSRF-TOKEN" content="{{csrf_token()}}">
	@include('App.Template.styles')
	@yield('PageStyles')
	@yield('PageMeta')
	<title>@yield('PageTitle')</title>
</head>
<body class="home-page">
@include('App.Template.header')

@yield('content')

@include('App.Template.footer')
<!-- Start JS -->
@include('App.Template.scripts')
@yield('PageScripts')
<!-- End JS -->
</body>
</html>

resources/views/App/Template/navbar.blade.php
<!-- desktop menu -->
<div class="menu-area d-none d-md-block">
	<ul class="menu text-center clr-ff my-4">
		<li class="active">
			<a href="{{route('App.Home')}}">Home</a>
		</li>
		<li id="have-submenu" class="have-submenu">
			<a href="{{route('App.form.showBuyingForm')}}">Buy</a>
		</li>
		<li>
			<a href="{{route('App.form.showSellingForm')}}">Sell</a>
		</li>
		<li>
			<a href="{{route('App.house.index')}}">Listings</a>
		</li>
		<li>
			<a href="{{route('App.blog.archive')}}">Blog</a>
		</li>
		<li>
			<a href="{{route('App.about')}}">About</a>
		</li>
		<li>
			<a href="{{route('App.contact')}}">Contact Us</a>
		</li>
	</ul>
</div>
<!-- mobile-menu -->
<div class="off-con text-right d-block d-md-none">
	<div class="mobile-menu">
		<div class="m-menu-btn">
			<a id="m-menu-btn">
				<i class="fal fa-bars"></i>
			</a>
		</div>
		<section class="m-menu" id="m-menu">
			<div class="m-menu-box" id="m-menu-box">
				<a id="m-menu-close" class="m-menu-close">
					<i class="fal fa-times clr-red"></i>
				</a>
				<div class="logo-area text-center">
					<a href="#">
						<img src="images/logo.png" alt="">
					</a>
				</div>
				<ul class="hd-font">
					<li>
						<a href="index.html">
							home
						</a>
					</li>
					<li>
						<a class="have-submenu-mobile" data-toggle="collapse" href="#ul-submenu-mobile" role="button" aria-expanded="false" aria-controls="collapseExample">
							buyer
							<i class="fal fa-chevron-down clr-ef ml-1"></i>
						</a>
						<div class="collapse" id="ul-submenu-mobile">
							<div class=" card-body m-0 p-0">
								<ul class="ul-submenu-mob mt-0">
									<li>
										<a href="#">
											submenu01
										</a>
									</li>
									<li>
										<a href="#">
											submenu01
										</a>
									</li>
									<li>
										<a href="#">
											submenu01
										</a>
									</li>
									<li>
										<a href="#">
											submenu01
										</a>
									</li>
								</ul>
							</div>
						</div>
					</li>
					<li>
						<a href="#">
							seller
						</a>
					</li>
					<li>
						<a href="#">
							Contact us
						</a>
					</li>
					<li>
						<a href="#">about amir</a>
					</li>
				</ul>
			</div>
			<div class="m-overly" id="m-overly"></div>
		</section>
	</div>
</div>

resources/views/App/Template/paginate.blade.php
@if($paginator->hasPages())
	<div class="row mt-5">
		<div class="col-12">
			<nav aria-label="archive-pagination">
				<ul class="pagination justify-content-center">
					@if($paginator->onFirstPage())
						<li class="page-item disabled">
							<span class="page-link">Previous</span>
						</li>
					@else
						<li class="page-item">
							<a class="page-link" href="{{$paginator->previousPageUrl()}}">Previous</a>
						</li>
					@endif
					@foreach($elements as $element)
						@if(is_string($element))
							<li class="page-item"><a class="page-link" href="javascript:;">{{$element}}</a></li>
						@endif
						@if(is_array($element))
							@foreach($element as $page => $url)
								@if($page == $paginator->currentPage())
									<li class="page-item active">
										<span class="page-link">{{$page}}<span class="sr-only">(current)</span></span>
									</li>
								@else
									<li class="page-item"><a class="page-link" href="{{$url}}">{{$page}}</a></li>
								@endif
							@endforeach
						@endif
					@endforeach
					@if ($paginator->hasMorePages())
						<li class="page-item">
							<a class="page-link" href="{{ $paginator->nextPageUrl() }}">Next</a>
						</li>
					@else
						<li class="page-item disabled">
							<span class="page-link">Next</span>
						</li>
					@endif
				</ul>
			</nav>
		</div>
	</div>
@endif

resources/views/App/Template/scripts.blade.php
<script type="text/javascript" src="/js/buttons.js"></script>
<script type="text/javascript" src="/js/jquery-min.js"></script>
<script type="text/javascript" src="/js/popper.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-material-design.min.js"></script>
<script type="text/javascript" src="/js/material-kit.min.js"></script>
<script type="text/javascript" src="/js/moment.min.js"></script>
<script type="text/javascript" src="/js/nouislider.min.js"></script>
<script type="text/javascript" src="/js/jasny-bootstrap.min.js"></script>
<script type="text/javascript" src="/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="/js/custom.js"></script>
<script type="text/javascript" src="/js/contant.js"></script>
<script type="text/javascript" src="/js/auth.js"></script>


<script>
    let Auth = {{ (auth()->check()?'true':'false') }} ;
    csrfToken = {
        tag: document.querySelector('meta[name="X-CSRF-TOKEN"]'),
        set: function (newCSRF) {
            this.tag.setAttribute('content', newCSRF)
        },
        get: function () {
            return this.tag.getAttribute('content')
        }
    }
</script>

resources/views/App/Template/styles.blade.php
<link rel="stylesheet" href="/css/material-kit.min.css" />
<link rel="stylesheet" type="text/css" href="/css/fontawesome.min.css">
<link rel="stylesheet" type="text/css" href="/css/light.min.css">
<link rel="stylesheet" type="text/css" href="/css/brands.min.css">
<link rel="stylesheet" type="text/css" href="/css/jasny-bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/css/owl.carousel.min.css">
<link rel="stylesheet" type="text/css" href="/css/owl.theme.default.min.css">
<link rel="stylesheet" type="text/css" href="/css/style.css">
<link rel="stylesheet" type="text/css" href="/css/responsive.css">