routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group( [ 'namespace' => 'App' , 'as' => 'app-auth.' ] , function() {
	\Illuminate\Support\Facades\Auth::routes();
} );
Route::group( [ 'as' => 'admin-auth.' , 'prefix' => 'v-admin' , 'namespace' => 'Admin' ] , function() {
	Route::redirect( '' , 'v-admin/login' );
	\Illuminate\Support\Facades\Auth::routes( [ 'register' => FALSE , 'emailVerify' => FALSE ] );

} );
Route::group( [ 'namespace' => 'Admin' , 'prefix' => 'v-admin' , 'as' => 'admin.' , 'middleware' => 'auth:admin' ] , function() {
	Route::get( '' , 'AdminController@dashboard' )->name( 'dashboard' );
	Route::group(['prefix'=>'profile','as'=>'profile.'],function(){
		Route::get('','AdminController@profile')->name('show');
		Route::post('edit/profile','AdminController@change')->name('change');
		Route::post('edit/password','AdminController@password')->name('password');
	});
	Route::group( [ 'prefix' => 'users' , 'as' => 'user.' ] , function() {
		Route::get( '' , 'UserController@index' )->name( 'index' );
		Route::delete( 'delete/{user}' , 'UserController@delete' )->name( 'delete' );
		Route::get( '/show/{user}' , 'UserController@show' )->name( 'show' );
	} );
	Route::group( [ 'prefix' => 'contants' , 'as' => 'contant.' ] , function() {
		Route::get( 'delete/{contant}' , 'ContantController@delete' )->name( 'delete' );
		Route::get( '' , 'ContantController@index' )->name( 'index' );
		Route::get('create','ContantController@create')->name('create');
		Route::post('store','ContantController@store')->name('store');
	} );
	Route::group( [ 'prefix' => 'account' , 'as' => 'account.' ] , function() {
		Route::get( '' , 'AdminController@index' )->name( 'index' );
		Route::get( 'create' , 'AdminController@create' )->name( 'create' );
		Route::post( 'create' , 'AdminController@store' )->name( 'store' );
		Route::delete( 'delete/{admin}' , 'AdminController@delete' )->name( 'delete' );
		Route::get( 'edit/{admin}' , 'AdminController@edit' )->name( 'edit' );
		Route::patch( 'update/{admin}' , 'AdminController@update' )->name( 'update' );
		Route::get('show/{admin}' , 'AdminController@show')->name('show');
	} );
	Route::group( [ 'prefix' => 'houses' , 'namespace' => 'House' , 'as' => 'houses.' ] , function() {
		Route::get( '' , 'HousesController@index' )->name( 'index' );
		Route::get( '/create' , 'HousesController@create' )->name( 'create' );
		Route::post( '/create' , 'HousesController@store' )->name( 'store' );
		Route::get( '/edit/{house}' , 'HousesController@edit' )->name( 'edit' );
		Route::post( '/edit/{house}' , 'HousesController@update' )->name( 'update' );
		Route::get( '/delete/{house}' , 'HousesController@delete' )->name( 'delete' );
    } );
	Route::group( [ 'prefix' => 'tickets' , 'as' => 'ticket.' ] , function() {
		Route::get( '' , 'TicketController@index' )->name( 'index' );
		Route::post( 'edit/{id}' , 'TicketController@update' )->name( 'update' );
		Route::get( 'edit/{ticket}' , 'TicketController@edit' )->name( 'edit' );
	} );
	Route::group( [ 'prefix' => 'agents' , 'as' => 'agent.' ] , function() {
		Route::get( '' , 'AgentController@index' )->name( 'index' );
		Route::get( 'edit/{agent}' , 'AgentController@edit' )->name( 'edit' );
		Route::post( 'edit/{id}' , 'AgentController@update' )->name( 'update' );
	} );
	Route::group( [ 'prefix' => 'blogs' , 'as' => 'blog.' , 'namespace' => 'Blog' ] , function() {
		Route::group( [ 'prefix' => 'categories' , 'as' => 'categories.' ] , function() {
            Route::get( '' , 'CategoryController@index' )->name( 'index' );
            Route::get( 'create' , 'CategoryController@create' )->name( 'create' );
			Route::post( 'create' , 'CategoryController@store' )->name( 'store' );
			Route::get( 'edit/{category}' , 'CategoryController@edit' )->name( 'edit' );
			Route::patch( 'update/{category}' , 'CategoryController@update' )->name( 'update' );
			Route::delete( 'delete/{category}' , 'CategoryController@delete' )->name( 'delete' );
		} );
		Route::group( [ 'prefix' => 'comments' , 'as' => 'comments.' ] , function() {
			Route::get( '' , 'CommentController@index' )->name( 'index' );
			Route::get( 'delete/{comment}' , 'CommentController@delete' )->name( 'delete' );
			Route::post( 'confirm/{comment}' , 'CommentController@confirm' )->name( 'confirm' );
			Route::post( 'update' , 'CommentController@update' )->name( 'update' );
		} );
		Route::group( [ 'prefix' => 'articles' , 'as' => 'articles.' ] , function() {
			Route::get( 'create' , 'ArticleController@create' )->name( 'create' );
			Route::get( '' , 'ArticleController@index' )->name( 'index' );
			Route::post( 'store' , 'ArticleController@store' )->name( 'store' );
			Route::get( 'delete/{article}' , 'ArticleController@delete' )->name( 'delete' );
			Route::get( 'edit/{article}' , 'ArticleController@edit' )->name( 'edit' );
			Route::post( 'update/{article}' , 'ArticleController@update' )->name( 'update' );
			Route::post('uploadImage' , 'ArticleController@uploadImage')->name('uploadImage');
	} );
		} );
	Route::group( [ 'prefix' => 'options' , 'as' => 'options.' ] , function() {
		Route::post('up-image' , 'OptionController@UploadImage') ->name('upImage');
		Route::group(['prefix'=>'about' , 'as'=>'about.'],function(){
			Route::get('','OptionController@about')->name('view');
			Route::post('','OptionController@saveAbout')->name('store');
		});
		Route::group(['prefix'=>'form/buyer' , 'as'=>'form.buyer.'],function(){
			Route::get('','OptionController@buyer')->name('view');
			Route::post('','OptionController@saveBuyer')->name('store');
		});
		Route::group(['prefix'=>'form/seller' , 'as'=>'form.seller.'],function(){
			Route::get('','OptionController@seller')->name('view');
			Route::post('','OptionController@saveSeller')->name('store');
		});
		Route::group( [ 'prefix' => 'home' , 'as' => 'home' ] , function() {
            Route::get( '' , 'OptionController@Home' );
            Route::post( '' , 'OptionController@UpdateHome' );
			Route::post( 'upload/ImageSlide' , 'OptionController@imageSlider' )->name( '.imageSlider' );
			Route::post( 'upload/ImageQSearch' , 'OptionController@ImageQSearch' )->name( '.ImageQSearch' );
		} );
		Route::group( [ 'prefix' => 'general' , 'as' => 'general' ] , function() {
			Route::get( '' , 'OptionController@General' );
			Route::post( '' , 'OptionController@UpdateGeneral' );
			Route::post('add/media','OptionController@addMedia')->name('addMedia');
		} );
	} );
} );
Route::group( [ 'as' => 'App.' , 'namespace' => 'App' ] , function() {
	Route::get( '' , "HomeController@Home" )->name( 'Home' );
	Route::group( [ 'as' => 'profile' , 'prefix' => 'profile' , 'middleware' => 'auth' ] , function() {
        Route::get( '' , 'UserController@profile' )->name( '' );
        Route::post( 'change-avatar' , 'UserController@avatar' )->name( '.change-avatar' );
		Route::post( 'changePassword' , 'UserController@changePassword' )->name( '.changePassword' );
		Route::post( 'updateProfile' , 'userController@update' )->name( '.update' );
	} );
	Route::get('about','PageController@about')->name('about');
	Route::get( 'contact' , 'ContantController@contact' )->name( 'contact' );
	Route::group( [ 'prefix' => 'blogs' , 'as' => 'blog.' , 'namespace' => 'Blog' ] , function() {
		Route::get( 'article/{article}' , 'ArticleController@show' )->name( 'show' );
		Route::get( 'archive' , 'ArticleController@archive' )->name( 'archive' );
        Route::post('store/{article}', 'ArticleController@store')->name('store');
	} );
	Route::group( [ 'prefix' => 'houses' , 'as' => 'house.' , 'namespace' => 'House' ] , function() {
		Route::get( '/{MLSNumber}/{Address}' , 'HouseController@show' )->name( 'show' );
		Route::get( '' , 'HouseController@archive' )->name( 'index' );
	} );
	Route::group( [ 'prefix' => 'forms' , 'as' => 'form.' ] , function() {
		Route::post( 'buy' , 'TicketController@Buy' )->name( 'buy' );
		Route::get( 'sell' , 'TicketController@showSellingForm' )->name( 'showSellingForm' );
		Route::get( 'buy' , 'TicketController@showBuyingForm' )->name( 'showBuyingForm' );
		Route::post( 'sell' , 'TicketController@Sell' )->name( 'sell' );
		Route::post( 'ticket' , 'TicketController@contact' )->name( 'TicketContact' );
        Route::post( 'store' , 'TicketController@store' )->name( 'store' );
    } );
} );

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;

/**
 * App\User
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property \Illuminate\Support\Carbon|null $email_verified_at
 * @property string $password
 * @property string|null $phone
 * @property string|null $avatar
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Ticket[] $tickets
 * @property-read int|null $tickets_count
 * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User query()
 * @method static \Illuminate\Database\Eloquent\Builder|User whereAvatar($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePhone($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'phone', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($value){
    	$this->attributes['password'] =  ( Hash::needsRehash( $value ) ? Hash::make( $value ) : $value );
    }


    public function tickets(){
    	return $this->hasMany(Ticket::class);
    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Ticket;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index(User $user){
            $p=\request()->all();
            $users=User::query();
        if ( isset( $p[ 'name' ] ) && $p[ 'name' ] != NULL ) {
            $users = $users->where( 'name' , 'LIKE' , '%' . $p[ 'name' ] . '%' );
        }
        if ( isset( $p[ 'email' ] ) && $p[ 'email' ] != NULL ) {
            $users = $users->where( 'email' , $p[ 'email' ] );
        }
        $users=$users->get();
        return view('Admin.Users.index',compact('users'));
    }
    public function delete(User $user){
        $user->delete();
        return back()->with('delete','The user delete successfully');
    }
    public function show(User $user){

        return view('Admin.Users.show',compact('user'));
    }
}

app/Http/Controllers/App/UserController.php
<?php

namespace App\Http\Controllers\App;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
	public function profile ()
	{
		$user = auth()->user();
		$requests = $user->tickets;
		return view( 'App.profile' , [ 'user' => $user , 'requests' => $requests ] );
	}
	
	public function update ( Request $request )
	{
		$user = $request->user();
		$valid = validator( $request->all() , [
			'name'  => 'required' ,
			'email' => [ 'required' , 'email' , Rule::unique( 'users' )->ignore( $user->id ) ] ,
			'phone' => 'required|'
		] )->errors();
		if ( $valid->any() ) {
			$response = [
				'message'    => $valid->first() ,
				'success'    => FALSE ,
				'csrf-token' => csrf_token()
			];
			return response()->json( $response );
		}
		$user->update($request->all());
		$response = [
			'message'    =>  'Your Profile Has Been Successfully Updated',
			'success'    => TRUE ,
			'csrf-token' => csrf_token()
		];
		return response()->json( $response );
	}
	
	public function avatar ( Request $request )
	{
		$valid = validator( $request->all() , [ 'avatar' => 'required|mimes:jpeg,jpg,png' ] )->errors();
		$user = $request->user();
		if ( $valid->any() ) {
			$response = [
				'message'    => $valid->first() ,
				'success'    => FALSE ,
				'csrf-token' => csrf_token()
			];
			return response()->json( $response );
		}
		$file = $request->file( 'avatar' );
		$file->hashName();
		$file->extension();
		$file = $file->store( 'users/avatar' , [ 'disk' => 'public' ] );
		$user->avatar = Storage::url( $file );
		$user->save();
		$response = [
			'avatar'     => [
				'link' => $user->avatar
			] ,
			'message'    => 'Your Avatar Has Been Successfully Updated' ,
			'success'    => TRUE ,
			'csrf-token' => csrf_token()
		];
		return response()->json( $response );
	}
	
	public function changePassword ( Request $request )
	{
		$user = $request->user();
		$valid = validator( $request->all() , [
			'current-password' => 'required|password' ,
			'password'         => 'required|confirmed'
		] )->errors();
		if ( $valid->any() ) {
			$response = [
				'message'    => $valid->first() ,
				'success'    => FALSE ,
				'csrf-token' => csrf_token()
			];
			return response()->json( $response );
		}
		$user->password = $request->password;
		$user->save();
		$response = [
			'redirect'   => route( 'App.Home' ) ,
			'message'    => 'Your Password Has Been Successfully Changed' ,
			'success'    => TRUE ,
			'csrf-token' => csrf_token()
		];
		return response()->json( $response );
	}
}

resources/views/Admin/Users/index.blade.php
@extends('Admin.Template.layout')
@section('content')
	@include('Admin.Template.notification')
	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<a style="float: right" href="{{route('admin.account.create')}}">
				<button type="button" class="btn btn-success btn-sm ">create</button>
			</a>
			<h6 class="m-0 font-weight-bold text-primary">List Users</h6>
		</div>
		<div class="card-body">
			<form class="" action="{{request()->fullUrl()}}">
				<div class="row" style="padding-bottom: 10px;">
					<div class="col-md-3 col-sm-12 col-xl-2">
						<input type="hidden" name="type" value="{{request('type')}}">
						<input type="text" class="form-control" placeholder="Name" name="name" value="{{request('name')}}">
					</div>
					<div class="col-md-3 col-sm-12 col-xl-2">
						<input type="email" class="form-control" placeholder="Email" name="email" value="{{request('email')}}">
					</div>
					<div class="col-sm-2 col-sn-12 col-xl-2">
						<button type="submit" class="btn btn-outline-primary">Apply</button>
					</div>
				</div>
			</form>
			<table class="table table-bordered table-hover" border="5">
				<thead>
				<tr>
					<th style="text-align: center">Name</th>
					<th style="text-align: center">Email</th>
					<th style="text-align: center">Number tickets</th>
					<th>Settings</th>
				</tr>
				</thead>
				@foreach($users  as $user)
					<tr>
						<td style="text-align: center">{{$user->name}}</td>
						<td style="text-align: center">{{$user->email}}</td>
						<td style="text-align: center">{{$user->tickets->count()}}</td>
						<td>
							<div class="btn-group">
								<form action="{{route('admin.user.delete' , $user)}}" method="post">
									@csrf
									@method('delete')
									{{--                                <a href="{{route('admin.account.edit',$admin)}}" class="btn btn-warning btn-sm">Edit</a>--}}
									<button type="submit" class="btn btn-danger btn-sm">Delete</button>
									<a href="{{route('admin.user.show',$user)}}" target="_blank">
										<button type="button" class="btn btn-success btn-sm">ShowProfile</button>
									</a>
								</form>
							</div>
						</td>
					</tr>
				@endforeach
			</table>
		</div>
	</div>


@endsection

resources/views/Admin/Users/show.blade.php
@extends('Admin.Template.layout')
@section('css')
    <style>
        img.avatar {
            width: 100%;
        }
    </style>
@endsection
@section('content')
    <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="agent-container">

                <img class="avatar"
                     src="{{$user->avatar??'http://namehere.realtyninja.com/static/images/agents/med/1512073054_agent-placeholder-5.jpeg'}}">

                <div class="user-content">
                    <h4>{{$user->name}}</h4>

                    <p class="agent-phone">
                        <i class="fa fa-phone"></i> <a href="tel:604-123-4567">{{$user->phone}}</a>
                    </p>

                    <p class="agent-email">
                        <i class="fa fa-envelope"></i> <a href="mailto:linda@gmail.com">{{$user->email}}</a>
                    </p>
                    <p>
                        <i class="fa fa-envelope fa-5x fa-border icon-grey badge"></i>Number
                        ticket:{{$user->tickets->count()}}
                    </p>


                    <div class="clearfix"></div>
                </div>

            </div>

        </div>
        <div class="col-lg-9 col-md-8 col-sm-6 ">
            <h2>List tickets:</h2>
            <table class="table table-bordered table-hover" border="5">
                <thead>
                <tr>

                    <th style="text-align: center">ticket type</th>
                    <th style="text-align: center">state</th>
                    <th style="text-align: center">ticket date</th>

                </tr>
                </thead>

                @foreach($user->tickets as $ticket)
                    <tr>

                        <td style="text-align: center">{{$ticket->ticketType}}</td>
                        <td style="text-align: center">{{$ticket->state}}</td>
                        <td style="text-align: center">{{$ticket->created_at}}</td>


                    </tr>
                @endforeach

            </table>
        </div>
    </div>



@endsection